version: '3.9'

services:

  db:
    restart: always
    image: postgres:14.4-alpine3.16
    ports:
      - 5432:5432
    volumes:
      - db-cs:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=CSDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  api:
    restart: always
    build: .
    ports:
      - 3001:3000
    volumes:
      - .:/app_rest
    depends_on:
      - db
    # environment:
    #   - DB_NAME=csdb
    #   - DB_USER=csuser
    #   - DB_PASSWORD=Admin141189@
    #   - DB_HOST=postgres

volumes:
  db-cs: